name: C++ Windows CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -S . -B build -A Win32

    - name: Build
      run: cmake --build build --config Release
